name: flutter_demo
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  socket_io_client: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

 